---
language: ruby
dist: xenial
sudo: false
if: (type = pull_request) OR (tag IS present) OR (branch = master)
cache:
  directories:
    - "$HOME/.berkshelf"
services: docker
install:
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk -v 3
  - eval "$(chef shell-init bash)"
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
    -N DOCKER )
  - chef --version
env:
  global:
    - CHEF_LICENSE='accept'
  matrix:
    - CHEF_VERSION=14
    - CHEF_VERSION=15
    - CHEF_VERSION=16
jobs:
  include:
    - stage: Verify
      script: delivery local verify

    - stage: Acceptance
      script: kitchen test default-ubuntu-1604

    - script: kitchen test default-ubuntu-1804
      name: default-ubuntu-1804

    - script: kitchen test default-ubuntu-2004
      name: default-ubuntu-2004

    - script: kitchen test default-centos-7
      name: default-centos-7

    - script: kitchen test default-centos-7
      name: default-centos-8

    - script: kitchen test systemd-ubuntu-1604
      name: systemd-ubuntu-1604

    - script: kitchen test systemd-ubuntu-1804
      name: systemd-ubuntu-1804

    - script: kitchen test systemd-ubuntu-2004
      name: systemd-ubuntu-2004

    - script: kitchen test systemd-centos-7
      name: systemd-centos-7

    - script: kitchen test systemd-centos-7
      name: systemd-centos-8

notifications:
  slack:
    secure: Bh2Lb596AhPXzFOviP+pVhQaZxXN1ry3swomyXELNvKRbQPcdHNn4slgZXhWplRo1XQUsSGSBmrdwoNAWpvNGQnLTyz8hAI1wmUnc0KEF/4RGaKbzsuuhvctFbiSaO1u/Y9yZ1hT9RW6fbM4TepJ5+DoI0q9PxDRuXPnGd2RnWg=
